/**
 * Every image and film on the site, in one place.
 *
 * Renditions (sizes, blur placeholders, video paths) are generated by
 * scripts/media/build-almasi-media.mjs into media-data.json; the words — titles,
 * alt text, provenance — are written here by hand.
 *
 * Provenance is recorded honestly. `supplied` scenes are the developer's own
 * renders, retouched only to remove the marketing text baked into them.
 * `concept` scenes were generated in the same visual language to cover spaces
 * no render exists for yet. Both are CG and carry the artist's-impression note;
 * concept scenes are the first to replace when the architect's visualiser
 * delivers (docs/CONTENT_BRIEF.md lists them).
 */
import type { ResidenceType } from './residences';
import data from './media-data.json';

export type SceneId =
  | 'aerial'
  | 'street'
  | 'arrival'
  | 'lobby'
  | 'pool'
  | 'restaurant'
  | 'gym'
  | 'wellness'
  | 'cowork'
  | 'parking'
  | 'living-2br'
  | 'two-kitchen'
  | 'one-living'
  | 'one-bedroom'
  | 'one-kitchen'
  | 'ph-living'
  | 'ph-kitchen'
  | 'ph-bedroom'
  | 'ph-bath'
  | 'ph-terrace'
  | 'view'
  | 'plan-1br'
  | 'plan-2br'
  | 'plan-ph';

export type Provenance = 'supplied' | 'concept';

interface SceneWords {
  title: string;
  alt: string;
  provenance: Provenance;
  /** object-position for cover crops, so the subject survives a portrait screen. */
  focus?: string;
}

export interface Rendition {
  src: string;
  width: number;
  height: number;
  blur: string;
  video?: { hd: string; sd: string; poster: string; seconds: number };
}

export interface Scene extends SceneWords, Rendition {
  id: SceneId;
}

const WORDS: Record<SceneId, SceneWords> = {
  aerial: {
    title: 'Kimihurura from the air',
    alt: 'Aerial view at dusk over the green hills of Kimihurura, Kigali, with Almasi Residences on a rise in the middle distance.',
    provenance: 'concept',
    focus: '50% 60%',
  },
  street: {
    title: 'Arrival on KG 15 Ave',
    alt: 'Almasi Residences from KG 15 Ave at dusk: a stone and walnut facade with deep glass balconies behind a gatehouse and palms.',
    provenance: 'supplied',
    focus: '58% 50%',
  },
  arrival: {
    title: 'The porte-cochère',
    alt: 'The covered drop-off at dusk: a walnut canopy, a water wall and the glowing lobby behind a curved driveway.',
    provenance: 'supplied',
    focus: '55% 55%',
  },
  lobby: {
    title: 'Reception',
    alt: 'The double-height reception lobby in travertine and walnut, with a marble desk, a lounge and a ring chandelier.',
    provenance: 'concept',
  },
  pool: {
    title: 'The pool deck',
    alt: 'The residents’ fifteen-metre pool at blue hour, lit from below, with loungers and the building rising behind.',
    provenance: 'concept',
  },
  restaurant: {
    title: 'The restaurant',
    alt: 'The residents’ restaurant: olive leather banquettes, marble tables laid for dinner and a backlit bar.',
    provenance: 'concept',
  },
  gym: {
    title: 'The fitness studio',
    alt: 'The fitness studio with strength equipment and treadmills facing full-height glass and the hills at dusk.',
    provenance: 'concept',
  },
  wellness: {
    title: 'Sauna and massage',
    alt: 'The wellness suite: a glass-fronted cedar sauna beside a calm massage room in travertine.',
    provenance: 'concept',
  },
  cowork: {
    title: 'The co-working lounge',
    alt: 'The residents’ co-working lounge with a long oak table, brass lamps and walnut-slat walls.',
    provenance: 'concept',
  },
  parking: {
    title: 'Basement parking',
    alt: 'The basement car park in board-formed concrete, with EV charging and a walnut-lined lift lobby.',
    provenance: 'concept',
  },
  'living-2br': {
    title: 'A two-bedroom living room',
    alt: 'A two-bedroom living and dining room at sunset, opening onto a balcony above the Kigali hills.',
    provenance: 'supplied',
    focus: '40% 55%',
  },
  'two-kitchen': {
    title: 'A two-bedroom kitchen',
    alt: 'An open kitchen with a marble island, walnut joinery and glass pendant lights.',
    provenance: 'supplied',
  },
  'one-living': {
    title: 'A one-bedroom living room',
    alt: 'A one-bedroom living room and kitchen at dusk, with a balcony over the valley.',
    provenance: 'supplied',
    focus: '45% 55%',
  },
  'one-bedroom': {
    title: 'A one-bedroom bedroom',
    alt: 'A bedroom with a slatted walnut wall, an upholstered bed and a window onto the hills.',
    provenance: 'supplied',
  },
  'one-kitchen': {
    title: 'A one-bedroom kitchen',
    alt: 'A compact kitchen in walnut and marble with an integrated refrigerator.',
    provenance: 'supplied',
  },
  'ph-living': {
    title: 'Penthouse living and dining',
    alt: 'Penthouse living and dining room under a walnut ceiling, with a sunset over Kigali beyond the glass.',
    provenance: 'supplied',
    focus: '45% 55%',
  },
  'ph-kitchen': {
    title: 'The penthouse kitchen',
    alt: 'The penthouse kitchen with an island, walnut cabinetry and a lit staircase.',
    provenance: 'supplied',
  },
  'ph-bedroom': {
    title: 'The penthouse master suite',
    alt: 'A penthouse master bedroom with a lit walk-in closet and a dusk view over the city.',
    provenance: 'supplied',
    focus: '55% 55%',
  },
  'ph-bath': {
    title: 'The penthouse en-suite',
    alt: 'A marble en-suite with a freestanding stone bath in front of a window onto the hills at dusk.',
    provenance: 'concept',
  },
  'ph-terrace': {
    title: 'The penthouse roof terrace',
    alt: 'A private roof terrace with an infinity pool and loungers, facing the sunset over Kigali.',
    provenance: 'supplied',
    focus: '60% 50%',
  },
  view: {
    title: 'The view west over Kigali',
    alt: 'The sun setting over the hills of Kigali, seen from the roof terrace.',
    provenance: 'supplied',
  },
  'plan-1br': {
    title: 'One bedroom, furnished plan',
    alt: 'Indicative furnished plan of a one-bedroom residence: living and dining, kitchen, bedroom, bathroom and balcony.',
    provenance: 'concept',
  },
  'plan-2br': {
    title: 'Two bedroom, furnished plan',
    alt: 'Indicative furnished plan of a two-bedroom residence: living and dining, island kitchen, two bedrooms, two bathrooms and a balcony.',
    provenance: 'concept',
  },
  'plan-ph': {
    title: 'Penthouse, furnished plan',
    alt: 'Indicative furnished plan of a three-bedroom penthouse with a study and a wrap-around terrace.',
    provenance: 'concept',
  },
};

const RENDITIONS = data as Partial<Record<SceneId, Rendition>>;

/** Scenes whose renditions exist. A missing one is a build step not run, not a crash. */
export function hasScene(id: SceneId): boolean {
  return RENDITIONS[id] !== undefined;
}

const FALLBACK: SceneId = 'street';

export function scene(id: SceneId): Scene {
  const rendition = RENDITIONS[id] ?? RENDITIONS[FALLBACK];
  if (!rendition) {
    throw new Error('No media renditions — run scripts/media/build-almasi-media.mjs');
  }
  return { id, ...WORDS[id], ...rendition };
}

/** What each residence type shows: its opening image, its spaces and its plan. */
export const TYPE_MEDIA: Record<
  ResidenceType,
  { hero: SceneId; spaces: { id: SceneId; label: string }[]; plan: SceneId }
> = {
  'one-bedroom': {
    hero: 'one-living',
    spaces: [
      { id: 'one-living', label: 'Living and dining' },
      { id: 'one-kitchen', label: 'Kitchen' },
      { id: 'one-bedroom', label: 'Bedroom' },
      { id: 'ph-bath', label: 'Bathroom' },
      { id: 'view', label: 'From the balcony' },
    ],
    plan: 'plan-1br',
  },
  'two-bedroom': {
    hero: 'living-2br',
    spaces: [
      { id: 'living-2br', label: 'Living and dining' },
      { id: 'two-kitchen', label: 'Kitchen' },
      { id: 'one-bedroom', label: 'Main bedroom' },
      { id: 'ph-bath', label: 'En-suite' },
      { id: 'view', label: 'From the balcony' },
    ],
    plan: 'plan-2br',
  },
  penthouse: {
    hero: 'ph-living',
    spaces: [
      { id: 'ph-living', label: 'Living and dining' },
      { id: 'ph-kitchen', label: 'Kitchen' },
      { id: 'ph-bedroom', label: 'Master suite' },
      { id: 'ph-bath', label: 'En-suite' },
      { id: 'ph-terrace', label: 'Terrace' },
    ],
    plan: 'plan-ph',
  },
};

export const PROVENANCE_NOTE: Record<Provenance, string> = {
  supplied: 'Artist’s impression.',
  concept: 'Concept visual. Final interior design by the architect.',
};
